name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Run deno fmt
        run: deno fmt --check

      - name: Run deno lint
        run: deno lint

      - name: Run deno test
        if: matrix.os == 'macOS-latest'
        run: |
          brew install libssh2
          deno test --allow-ffi --unstable

      - name: Run deno test
        if: matrix.os == 'ubuntu-latest'
        run: |
          # https://github.com/denoland/deno/blob/1848c7e361f1a3a33487b60ab6fcb61ed1f62273/.github/workflows/ci.yml#L155
          sudo apt remove --purge -y man-db
          sudo apt update
          sudo apt install build-essential git autoconf libtool libssl-dev -y
          pushd /tmp
          git clone https://github.com/libssh2/libssh2.git libssh2
          cd libssh2
          autoreconf -vfi
          ./configure 
          make
          make check
          sudo make install
          popd

          deno test --allow-ffi --unstable

      - name: Run deno test
        if: matrix.os == 'windows-latest'
        run: |
          choco install openssh
          deno test --allow-ffi --unstable
